### ISSUE TITLE
Detecting pg_graphql

### ISSUE THREAD

**Issue by whymlaszlo** [dolevf/graphw00f#34]
Is it possible to detect [pg_graphql](https://github.com/supabase/pg_graphql) applications?

**Comment by dolevf** [comment]
the pg_graphql repository includes a GraphQL server written in Rust from scratch with an AST parser. Now, I'm not entirely sure if this GraphQL server is used by pg_graphql or it's just there to make demoing pg_graphql easier.

Eitherway, I added it since it's fingerprintable so why not.

https://github.com/dolevf/graphw00f/releases/tag/1.1.15
